trigger:
  branches:
    include:
    - main
    exclude:
    - /*
  paths:  
    exclude:
    - docs/*
    - documents/*
    - .devcontainer/*
    - terraform/bootstrap/*
    - terraform/templates/*
pool:
  vmImage: ubuntu-latest

stages:

  - stage: CI
    displayName: Continuous Integration
    jobs: 
    - job: CIvalidation
    variables:
    - group: tftec-iac-vars
  - template: stages/stages-ci.yml


  - stage: CD
    condition: succeeded() 
    displayName: Continuous Deployment
    jobs: 
    - job: "CD"
    variables:
    - group: tftec-iac-vars
  - template: stages/stages-cd.yml