stages:
- stage: CI_Stage
  variables:
    - group: tftec-iac-vars
  displayName: Continuous Integration
  jobs:
  - job: Terraform_Init
    displayName: Teste de Inicialização Terraform
    steps:
      - task: TerraformCLI@0
        displayName: Terraform init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-reconfigure'
          backendType: 'azurerm'
          backendServiceArm: 'tftec-devops'
          backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
          backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
          backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
          backendAzureRmKey: '$(TF-BACKEND-KEY)'
          allowTelemetryCollection: true

  - job: Terraform_Validate
    dependsOn: Terraform_Init
    displayName: Validação do Código
    steps:
      - task: TerraformCLI@0
        displayName: Terraform Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-reconfigure'
          backendType: 'azurerm'
          backendServiceArm: 'tftec-devops'
          backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
          backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
          backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
          backendAzureRmKey: '$(TF-BACKEND-KEY)'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        displayName: Terraform Validate
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        displayName: Terraform Format
        inputs:
          command: 'fmt'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-check -diff'
          allowTelemetryCollection: true

  - job: Terraform_Plan
    dependsOn: Terraform_Validate
    displayName: Planejamento do Deploy
    steps:
      # Inicializa o backend remoto antes de qualquer operação de workspace
      - task: TerraformCLI@0
        displayName: Terraform Init para Workspace
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-reconfigure'
          backendType: 'azurerm'
          backendServiceArm: 'tftec-devops'
          backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
          backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
          backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
          backendAzureRmKey: '$(TF-BACKEND-KEY)'
          allowTelemetryCollection: true

      # Tenta selecionar o workspace existente ou cria se não existir
      - script: |
          terraform workspace select live || terraform workspace new live
        displayName: "Select or Create Workspace"
      
      - task: TerraformCLI@0
        displayName: Terraform Plan
        inputs:
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          environmentServiceName: 'tftec-devops'
          commandOptions: '-out=main.tfplan -var-file=../env/aovivo-sp-24/aovivosp24.tfvars'
          allowTelemetryCollection: true
          publishPlanResults: 'Terraform Plan' 
